### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by zjutnlper** [zefanZhang-cn/CAMIM#2]
self.model_resnet50 = timm.create_model('resnet50', pretrained=True, pretrained_cfg_overlay=dict(
            file='resnet50_a1_0-14fe96d1.pth'))  # get the pre-trained ResNet model for the image 请问resnet50_a1_0-14fe96d1.pth这个权重文件在哪可以下载，还是说普通的就行

**Comment by zjutnlper** [comment]
大佬你好请问resnet50_a1_0-14fe96d1.pth这个权重文件在哪可以下载，还是说普通的就行

**Comment by zefanZhang-cn** [comment]
可以参考该论文https://github.com/thecharm/TMR
